CREATE DATABASE IF NOT EXISTS uav_inspection
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE uav_inspection;
CREATE TABLE IF NOT EXISTS alarm_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_code VARCHAR(64) NOT NULL UNIQUE,
  device_code VARCHAR(64) NOT NULL,
  task_code VARCHAR(64),
  event_type VARCHAR(64) NOT NULL,
  weapon_type VARCHAR(64),
  confidence DECIMAL(5,4),
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  image_url VARCHAR(512),
  video_url VARCHAR(512),
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  event_time DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS uav_device (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_code VARCHAR(64) NOT NULL UNIQUE,
  device_name VARCHAR(128) NOT NULL,
  device_type VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inspection_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_code VARCHAR(64) NOT NULL UNIQUE,
  task_name VARCHAR(128) NOT NULL,
  device_code VARCHAR(64),
  status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
  plan_start_time DATETIME,
  plan_end_time DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
