// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PeCesiumVue: typeof import('./src/components/pe-cesium-vue/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    $t: (key: string, ...args: unknown[]) => string;
  }
}